Incremental updates

diff --git a/bin/packager b/bin/packager
--- a/bin/packager
+++ b/bin/packager
@@ -13,7 +13,7 @@ PLATFORMS="$PLATFORMS buildserver-debian:wheezy buildserver-debian:jessie builds
 mkdir -p $DESTINATION/
 mkdir -p "$tmpdir"/bin "$tmpdir"/results
 
-rsync -pav `dirname $0`/ "$tmpdir"/bin
+rsync -pav `dirname $0`/ "$tmpdir"/bin > /dev/null
 
 if [ -z $GIT_REPO ]; then
 	echo "Usage: $0 <url to git repository>"
@@ -47,8 +47,10 @@ echo "Cloning git repository $GIT_REPO "
 for i in $PLATFORMS; do
 	cd $tmpdir
 	rm -rf repo
-	git clone "$GIT_REPO" repo
-	docker run -i -t -v "$tmpdir":/build $i /build/bin/build_package
+	git clone "$GIT_REPO" repo > /dev/null
+	echo "Building package using $i docker image"
+	buildlog=`mktemp`
+	docker run -i -t -v "$tmpdir":/build $i /build/bin/build_package > $buildlog || fail "Failed to build package. Build log in $buildlog" 
 done
 
 echo "Finished building package"
diff --git a/bin/update_debian_repository b/bin/update_debian_repository
--- a/bin/update_debian_repository
+++ b/bin/update_debian_repository
@@ -4,7 +4,8 @@ DOCKER_IMAGE=buildserver:ubuntu-12.04
 PACKAGE_DIR=/var/cache/packages/
 TEMPDIR=`mktemp -d`
 set -e
-#trap "rm -rf $TEMPDIR" EXIT
+trap "rm -rf $TEMPDIR" EXIT
+#trap "echo please remember to clean up $TEMPDIR" EXIT
 
 
 main() {
@@ -19,18 +20,37 @@ main() {
 
 
 get_remote_repo() {
-	rsync -pav $REMOTE_REPOSITORY/ $TEMPDIR/
+	rsync -pa $REMOTE_REPOSITORY/ $TEMPDIR/
 }
 
 update_repository() {
 	cd $PACKAGE_DIR
 	for distro in * ; do
 		cd $TEMPDIR
-		find $PACKAGE_DIR/$distro -iname \*deb -exec reprepro includedeb $distro {} \;
+		#find $PACKAGE_DIR/$distro -iname \*deb -exec reprepro includedeb $distro {} \;
+		for i in `find $PACKAGE_DIR/$distro -iname \*deb` ; do
+ 			add_package_to_repository $i $TEMPDIR $distro \;
+		done
 	done
 }
+
+# Add a single package to a given repository
+
+add_package_to_repository() {
+	package=$1
+	repo=$2
+	distro=$3
+	cd $repo
+	package_name=`basename $package`
+	files_already_in_repo=`find $repo -iname $package_name`
+	if [ -z "$files_already_in_repo" ]; then
+		reprepro includedeb $distro $package
+	else
+		echo "$package is already here"
+	fi
+}
 push_remote_repo() {
-	rsync -pav $TEMPDIR/ $REMOTE_REPOSITORY/
+	rsync -pa $TEMPDIR/ $REMOTE_REPOSITORY/
 }
 fail() {
 	echo $@
